# Generated by Django 4.2.11 on 2026-06-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarios",
            name="imagen_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ventas",
            name="estado",
            field=models.CharField(default="Completada", max_length=20),
        ),
    ]
