# Generated by Django 4.2.11 on 2026-06-19 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_sucursales_productos_imagen_productos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("ci", models.CharField(max_length=20, unique=True)),
                ("telefono", models.CharField(max_length=20)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Creditos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_credito", models.DateField(auto_now_add=True)),
                ("precio_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad_cuotas", models.PositiveIntegerField()),
                ("cuota_mensual", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cuotas_pagadas", models.PositiveIntegerField(default=0)),
                (
                    "saldo_pendiente",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PAGANDO", "Pagando"),
                            ("PAGADO", "Pagado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("stock_descontado", models.BooleanField(default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.clientes"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.productos",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.usuarios"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PagosCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_cuota", models.PositiveIntegerField()),
                ("monto_pagado", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_pago", models.DateTimeField(auto_now_add=True)),
                ("observacion", models.TextField(blank=True, null=True)),
                (
                    "credito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="users.creditos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecibosCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_recibo", models.CharField(max_length=50, unique=True)),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                (
                    "pago",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.pagoscredito",
                    ),
                ),
            ],
        ),
    ]
