# Generated by Django 4.2.11 on 2026-06-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usuarios_imagen_public_id_alter_ventas_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="productos",
            name="imagen_productos",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="productos",
            name="imagen_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
