# Generated by Django 4.2.11 on 2026-06-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_productos_imagen_productos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sucursales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("estado", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="productos",
            name="codigo_producto",
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name="productos",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.sucursales",
            ),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.sucursales",
            ),
        ),
        migrations.AddField(
            model_name="ventas",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.sucursales",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productos",
            unique_together={("codigo_producto", "sucursal")},
        ),
    ]
